name: uitcc
description: TCC
version: 1.2.0

environment:
  sdk: ">=3.0.0 <4.1.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_svg: ^2.0.6
  appwrite: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
   - assets/images/svg/
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700