name: uitcc
description: TCC
version: 1.7.0
publish_to: none

environment:
  sdk: ">=3.0.6 <4.1.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  flutter_svg: ^2.0.6
  appwrite: ^9.0.0
  google_fonts: ^5.1.0
  logger: ^2.0.1
  flutter_time_picker_spinner:
      git:
        url: https://github.com/brunoalm/flutter_time_picker_spinner.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
   - assets/images/svg/
   - assets/images/