final List<String> equipmentsRawList = [
  "Aparelho de blu ray",
  "Aparelho de DVD",
  "Aparelho de som",
  "Aquecedor de ambiente",
  "Aquecedor de mamadeira",
  "Aquecedor de marmita",
  "Ar condicionado",
  "Aspirador de pó",
  "Batedeira",
  "Boiler elétrico",
  "Bomba dágua",
  "Cafeteira",
  "Chaleira",
  "Churrasqueira",
  "Chuveiro",
  "Computador",
  "Enceradeira",
  "Espremedor de frutas",
  "Exaustor fogão",
  "Ferro de passar",
  "Fogão",
  "Forno",
  "Micro-ondas",
  "Freezer",
  "Frigobar",
  "Fritadeira elétrica",
  "Furadeira",
  "Geladeira",
  "Grill",
  "Home theater",
  "Impressora",
  "Lâmpada",
  "Lavadora de louças",
  "Lavadora de roupas",
  "Liquidificador",
  "Máquina de costura",
  "Modem de internet",
  "Monitor",
  "Multiprocessador",
  "Nebulizador",
  "Notebook",
  "Panela elétrica",
  "Prancha (chapinha)",
  "Projetor",
  "Rádio",
  "Roteador",
  "Sanduicheira",
  "Scanner",
  "Secador de cabelo",
  "Secadora de roupa",
  "Telefone sem fio",
  "Torneira",
  "Torradeira",
  "TV",
  "Ventilador",
  "Vídeo cassete",
  "Vídeo game",
  "Aparelho de barbear",
];
