final List<String> equipamentos = [
      "Aparelho de blu ray",
      "Aparelho de DVD",
      "Aparelho de som",
      "Aquecedor de ambiente",
      "Aquecedor de mamadeira",
      "Aquecedor de marmita",
      "Ar-condicionado tipo janela menor ou igual a 9.000 BTU/h",
      "Ar-condicionado tipo janela de 9.001 a 14.000 BTU/h",
      "Ar-condicionado tipo janela maior que 14.000 BTU/h",
      "Ar-condicionado tipo split menor ou igual a 10.000 BTU/h",
      "Ar-condicionado tipo split de 10.001 a 15.000 BTU/h",
      "Ar-condicionado tipo split de 15.001 a 20.000 BTU/h",
      "Ar-condicionado tipo split de 20.001 a 30.000 BTU/h",
      "Ar-condicionado tipo split maior que 30.000 BTU/h",
      "Aspirador de pó",
      "Batedeira",
      "Boiler elétrico de 200 L",
      "Bomba dágua 1/2 cv",
      "Bomba dágua 1/3 cv",
      "Cafeteira elétrica",
      "Cafeteira expresso",
      "Chaleira elétrica",
      "Churrasqueira elétrica",
      "Chuveiro elétrico - 4500 W",
      "Chuveiro elétrico - 5500 W",
      "Computador",
      "Enceradeira",
      "Espremedor de frutas",
      "Exaustor fogão",
      "Fax modem em stand by",
      "Ferro elétrico automático a seco - 1050 W",
      "Ferro elétrico automático a vapor - 1200 W",
      "Fogão elétrico - cook top",
      "(por queimador)",
      "Forno elétrico",
      "Forno micro-ondas - 25 L",
      "Freezer vertical/horizontal",
      "Freezer vertical frost free",
      "Frigobar",
      "Fritadeira elétrica",
      "Furadeira",
      "Geladeira 1 porta",
      "Geladeira 1 porta frost free",
      "Geladeira 2 portas",
      "Geladeira 2 portas frost free",
      "Grill",
      "Home theater - 350 W",
      "Impressora",
      "Lâmpada fluorescente compacta - 11 W",
      "Lâmpada fluorescente compacta - 15 W",
      "Lâmpada fluorescente compacta - 23 W",
      "Lâmpada incandescente - 40 W",
      "Lâmpada incandescente - 60 W",
      "Lâmpada incandescente - 100 W",
      "Lavadora de louças",
      "Lavadora de roupas",
      "Liquidificador",
      "Máquina de costura",
      "Modem de internet",
      "Monitor",
      "Monitor LCD",
      "Multiprocessador",
      "Nebulizador",
      "Notebook",
      "Panela elétrica",
      "Prancha (chapinha)",
      "Projetor",
      "Rádio elétrico pequeno",
      "Rádio relógio",
      "Roteador",
      "Sanduicheira",
      "Scanner",
      "Secador de cabelo - 1000 W",
      "Secadora de roupa",
      "Tanquinho",
      "Telefone sem fio",
      "Torneira elétrica - 3250 W",
      "Torradeira",
      'TV em cores - 14" (tubo)',
      'TV em cores - 29" (tubo)',
      'TV em cores - 32" (LCD)',
      'TV em cores - 40" (LED)',
      'TV em cores - 42" (LED)',
      "TV portátil",
      "Ventilador de mesa",
      "Ventilador de teto",
      "Videogame",
          ];