name: Build and Deploy Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3         

      - name: Instalação do Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: 3.13.0

      - name: Build Projeto
        run: |
          flutter pub get
          flutter build web

      - uses: actions/upload-artifact@v3
        with:
          name: temp
          path: build/web
  
      - uses: actions/download-artifact@v3
        with:
          name: temp
          path: web

      - name: Copia arquivo via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: web/*
          target: ${{ secrets.STORAGE_PATH }}

      - name: Substitui pelo arquivo em produção
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: ${{ secrets.WEB_SCRIPT }}